backend:
  name: github
  repo: TRegourd/necoh-www
  branch: main
media_folder: src/assets/image
public_folder: ""
publish_mode: editorial_workflow
collections:
  - label: "Accueil"
    name: "index"
    files:
      - label: "Contenu"
        name: "indexContent"
        file: "src/data/index.md"
        fields:
          - label: Entête
            name: indexHero
            widget: object
            fields:
              - { label: Titre de l'entête, name: title, widget: string }
              - { label: Sous-Titre de l'entête, name: subtitle, widget: text }
              - label: Texte Dynamique
                name: dynamicText
                widget: list
                fields:
                  - { label: Text, name: text, widget: string }
          - label: Avis Clients
            name: indexTestimonials
            widget: object
            fields:
              - { label: Titre de la section, name: title, widget: string }
              - {
                  label: Sous-Titre de la section,
                  name: subtitle,
                  widget: string,
                }
              - label: Avis Clients
                name: testimonials
                widget: list
                fields:
                  - { label: Nom, name: name, widget: string }
                  - {
                      label: Poste et/ou Entreprise,
                      name: position,
                      widget: string,
                    }
                  - { label: Avis, name: text, widget: text }
                  - { label: Avatar, name: avatar, widget: image }
          - label: Marques Necoh
            name: indexBrands
            widget: object
            fields:
              - { label: Titre de la section, name: title, widget: string }
              - {
                  label: Sous-Titre de la section,
                  name: subtitle,
                  widget: string,
                }
              - label: Marques
                name: brands
                widget: object
                fields:
                  - label: Necoh Comptabilité
                    name: comptabilite
                    widget: object
                    fields:
                      - { label: Titre, name: title, widget: string }
                      - { label: Description, name: desc, widget: string }
                      - { label: Titre du lien, name: link, widget: string }
                      - { label: Logo, name: logo, widget: image }
                  - label: Necoh Social
                    name: social
                    widget: object
                    fields:
                      - { label: Titre, name: title, widget: string }
                      - { label: Description, name: desc, widget: string }
                      - { label: Titre du lien, name: link, widget: string }
                      - { label: Logo, name: logo, widget: image }
                  - label: Necoh Juridique
                    name: juridique
                    widget: object
                    fields:
                      - { label: Titre, name: title, widget: string }
                      - { label: Description, name: desc, widget: string }
                      - { label: Titre du lien, name: link, widget: string }
                      - { label: Logo, name: logo, widget: image }
                  - label: Necoh Fiscalité
                    name: fiscalite
                    widget: object
                    fields:
                      - { label: Titre, name: title, widget: string }
                      - { label: Description, name: desc, widget: string }
                      - { label: Titre du lien, name: link, widget: string }
                      - { label: Logo, name: logo, widget: image }
                  - label: Necoh Audit
                    name: audit
                    widget: object
                    fields:
                      - { label: Titre, name: title, widget: string }
                      - { label: Description, name: desc, widget: string }
                      - { label: Titre du lien, name: link, widget: string }
                      - { label: Logo, name: logo, widget: image }
                  - label: Necoh Conseil
                    name: conseil
                    widget: object
                    fields:
                      - { label: Titre, name: title, widget: string }
                      - { label: Description, name: desc, widget: string }
                      - { label: Titre du lien, name: link, widget: string }
                      - { label: Logo, name: logo, widget: image }

  - label: "Services"
    name: "services"
    files:
      - label: "Comptabilité"
        name: "comptabilite"
        file: "src/data/services/comptabilite.md"
        fields:
          - label: Entête
            name: serviceHeader
            widget: object
            fields:
              - { label: Titre de l'entête, name: title, widget: string }
              - { label: Sous-Titre de l'entête, name: subtitle, widget: text }
              - { label: Logo, name: logo, widget: image }
              - { label: Couleur, name: color, widget: color }
          - label: Présentation
            name: serviceIntro
            widget: object
            fields:
              - { label: Titre, name: title, widget: string }
              - { label: Sous-Titre, name: subtitle, widget: text }
              - { label: Image, name: image, widget: image }
          - label: Services
            name: serviceFeatures
            widget: list
            fields:
              - { label: Titre, name: title, widget: string }
              - { label: Description, name: desc, widget: text }
              - { label: Logo, name: logo, widget: image }
          - label: Action
            name: serviceCTA
            widget: object
            fields:
              - { label: Titre, name: title, widget: string }
              - { label: Description, name: desc, widget: text }
      - label: "Audit"
        name: "audit"
        file: "src/data/services/audit.md"
        fields:
          - label: Entête
            name: serviceHeader
            widget: object
            fields:
              - { label: Titre de l'entête, name: title, widget: string }
              - { label: Sous-Titre de l'entête, name: subtitle, widget: text }
              - { label: Logo, name: logo, widget: image }
              - { label: Couleur, name: color, widget: color }
          - label: Présentation
            name: serviceIntro
            widget: object
            fields:
              - { label: Titre, name: title, widget: string }
              - { label: Sous-Titre, name: subtitle, widget: text }
              - { label: Image, name: image, widget: image }
          - label: Services
            name: serviceFeatures
            widget: list
            fields:
              - { label: Titre, name: title, widget: string }
              - { label: Description, name: desc, widget: text }
              - { label: Logo, name: logo, widget: image }
          - label: Action
            name: serviceCTA
            widget: object
            fields:
              - { label: Titre, name: title, widget: string }
              - { label: Description, name: desc, widget: text }

  - label: "A propos"
    name: "about"
    files:
      - label: "Contenu"
        name: "aboutContent"
        file: "src/data/about.md"
        fields:
          - label: Entête
            name: aboutHeader
            widget: object
            fields:
              - { label: Titre de l'entête, name: title, widget: string }
              - { label: Sous-Titre de l'entête, name: subtitle, widget: text }

  - label: "Outils et Liens utiles"
    name: "utils"
    files:
      - label: "Contenu"
        name: "utilsContent"
        file: "src/data/utils.md"
        fields:
          - label: Entête
            name: utilsHeader
            widget: object
            fields:
              - { label: Titre de l'entête, name: title, widget: string }
              - { label: Sous-Titre de l'entête, name: subtitle, widget: text }
          - label: Liens et outils
            name: utilsList
            widget: list
            fields:
              - { label: Nom, name: name, widget: string }
              - { label: Description, name: desc, widget: text }
              - { label: Logo, name: logo, widget: image }
              - { label: Lien, name: link, widget: string }
              - { label: Couleur, name: color, widget: color, required: false }

  - label: "Articles"
    name: "articles"
    files:
      - label: "Contenu de la page"
        name: "articlesContent"
        file: "src/data/articles.md"
        fields:
          - { label: Titre, name: title, widget: string }
          - { label: Sous Titre, name: subtitle, widget: string }
          - label: Catégorie
            name: category
            widget: list
            fields:
              - { label: Nom, name: name, widget: string }
              - label: Articles
                name: articles
                widget: list
                fields:
                  - { label: Titre, name: title, widget: string }
                  - { label: Description, name: description, widget: string }
                  - { label: Date, name: date, widget: date }
                  - { label: Auteur, name: author, widget: string }
                  - {
                      label: Photo de couverture,
                      name: thumbnail,
                      widget: image,
                    }
                  - { label: Texte, name: text, widget: markdown }
                  - label: Tags
                    name: tags
                    widget: list
                    fields:
                      - { label: Tag, name: tag, widget: string }
  - label: "Contact"
    name: "contact"
    files:
      - label: "Formulaire"
        name: "contactForm"
        file: "src/data/contactForm.md"
        fields:
          - { label: Titre, name: title, widget: string }
          - { label: Sous-Titre, name: subtitle, widget: string }
          - { label: Texte, name: text, widget: string }
      - label: "Coordonnées"
        name: "contactDetails"
        file: "src/data/contactDetails.md"
        fields:
          - { label: Titre, name: title, widget: string }
          - { label: Texte, name: text, widget: string }
          - { label: Téléphone, name: phone, widget: string }
          - { label: Email, name: email, widget: string }
          - { label: Adresse Ligne 1 (rue), name: addressLine1, widget: string }
          - {
              label: Adresse Ligne 2 (CP et Ville),
              name: addressLine2,
              widget: string,
            }
          - { label: Linkedin, name: linkedin, widget: string }
          - { label: Facebook, name: facebook, widget: string }
          - { label: Instagram, name: instagram, widget: string }
          - { label: Twitter, name: twitter, widget: string }
