name: Trigger Netlify Build
on:
  schedule:
    # Every 20 minutes
    - cron: '0-59/20 * * * *'
jobs:
  build:
    name: Netlify build
    runs-on: ubuntu-latest
    steps:
      - name: Curl request
        run: curl -X POST -d {} https://api.netlify.com/build_hooks/634fe97c819bc31562df1527
